---
- hosts: all
  sudo: true
  vars:
      document_root: /vagrant
  tasks:
      - name: Install stuff from Aptitude
        apt: name={{ item }} state=installed
        with_items:
          - git
          - tig
